### ISSUE TITLE
Opening Editor Do Not Auto-scrolls To Given Line Number

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/moonshine-feathersui-text-editor#10]
I see the an opening editor do not auto-scrolls to given line number in following scenarios:

1. Opening an editor caused by jump-to-definition activity (CMD/Ctrl+Click on definition) from any other editor
2. `Project > Search > Result` line double-click
![image](https://user-images.githubusercontent.com/24370870/156305427-ea709cd8-be93-4a25-8e25-0173bc654809.png)

**Comment by joshtynjala** [comment]
Confirmed. It appears to work correctly if the file was already open in a tab in Moonshine, but not if Moonshine needs to open the file in a new tab. I suspect that this is because the file hasn't completely loaded yet.
