### ISSUE TITLE
Cannot edit file after using find/search feature

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/moonshine-feathersui-text-editor#11]
Duplicate of: Moonshine-IDE/Moonshine-IDE/issues/988

Today I reproduced this issue using search instead of find feature

**Steps:**
1. Use the search feature (Ctrl+Shift+F).
2. Click on the changeset to go to the file (not just on a file name)
![image](https://user-images.githubusercontent.com/7197014/166921022-c559d436-6ecf-4713-9d44-8b9ee242931f.png)

3. Try editing the file. The caret is trapped on the first line of the file.
4. The editor is not listening for mouse events, but it is listening for keyboard events. If you manage to edit the file you will regain full control with your mouse.

**Additional circumstances:**
- My find result returned around 70 files and this is happening only for one of them
- It keeps happening for the same file even after Moonshine restart

**Comment by joshtynjala** [comment]
@Aszusz Unfortunately, I'm having trouble reproducing this issue.

I'm assuming that you are using a recent nightly build of Moonshine. Is that correct?

> My find result returned around 70 files and this is happening only for one of them

With this in mind, it may be that the combinations of files/projects along with the search queries that I've tried simply aren't correct to reproduce the issue. I'll keep trying a bit more, but I may need more information before I can do anything.

By the way, I don't have access to the MyAccount-Native-On-Royale repo, so I can't try to reproduce with that one (at least not without someone giving me permissions).

**Comment by joshtynjala** [comment]
I found a way to reproduce.

With the MoonshineSharedCore project open, search for `["NUMBER_"`. Then, open the result on line 143 of _KeyboardShortcut.as_.
