### ISSUE TITLE
Editor displays line numbers in the middle

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/moonshine-feathersui-text-editor#18]
In Apache Royale project when I jump to the source code of framework by clicking attribute in component like HGroup, VGroup (ex. gap, itemsVerticalAlign) line numbers are bing displayed in the middle of editor. Note that issue is not always reproducible. 

<img width="1424" alt="Screenshot 2023-09-14 at 15 22 21" src="https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/assets/24554795/f8bbaf41-2a0e-4ff6-81f9-7ca95003149b">

Moonshine IDE™ (Development)
Version 3.3.4, Build 3083, Player: 33.1(Harman)
Running on: Mac OS 13.5.2

**Comment by piotrzarzycki21** [comment]
Here is second way of reproducing this issue. Look what is happening when I do Enter on keyboard.


https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/assets/24554795/bf568810-c147-434d-b816-b89754d30fa0

**Comment by joshtynjala** [comment]
I'll try to take a look next week, @piotrzarzycki21!

**Comment by joshtynjala** [comment]
I found a way to consistently reproduce on my machine using the simple-text-editor sample when targeting Adobe AIR. I paste the following string into the editor, scroll to the right, and add a line break after the word "tempor"

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

I suspect that I know what's happening, and I have a pretty good idea of how to go about fixing it. I'll try get this done in the coming week.

**Comment by joshtynjala** [comment]
I've determined that this is a bug in Feathers UI, and I've committed a fix. However, I may be able to find a workaround for the current version of Feathers UI.

**Comment by joshtynjala** [comment]
I committed a workaround. It's possible that the issue may still reproduce in certain situations. If it does, let me know, and I'll try to adjust my workaround a bit.
