### ISSUE TITLE
Editor "Dark Mode"

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/moonshine-feathersui-text-editor#3]
Justin requested to have at some point that feature. If you could @joshtynjala comment on that how difficult it could be to implement.

**Comment by joshtynjala** [comment]
In Moonshine's syntax plugin for each language (such as `AS3SyntaxPlugin` for ActionScript 3), there is a line where the syntax highlighting colors are defined:

```action script
formatBuilder.setColorSettings(new SyntaxColorSettings());
```

Right now, it simply uses the defaults in the `SyntaxColorSettings` class. However, all of the variables in that class can be modified before passing it to `setColorSettings()`. This should allow us to define any color scheme we'd like, including a dark style. Like other editors, we could even include a variety of color schemes, not just light and dark. 

Example:

```actionscript
var colorSettings:SyntaxColorSettings = new SyntaxColorSettings();
colorSettings.keywordColor = 0x6666ff;
colorSettings.stringColor = 0xff6666;
formatBuilder.setColorSettings(colorSettings);
```

Additionally, we would need to change the `backgroundSkin` of the `TextEditor`/`LspTextEditor` to an appropriate background for the color scheme.

```actionscript
textEditor.backgroundSkin = new RectangleSkin(SolidColor(0x2f2f2f));
```

**Comment by DeafMan1983** [comment]
Very good and please add Font Size if I need big font because my eyes are not good and has less than 50 % of allowance of driving license. ( it means I can't read good with too small fonts )

**Comment by joshtynjala** [comment]
@DeafMan1983 Assuming that you are using moonshine-feathersui-text-editor in a Haxe project, the font size may be adjusted when you create an instance of the [`moonshine.editor.text.syntax.format.SyntaxFontSettings`](https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/blob/master/src/moonshine/editor/text/syntax/format/SyntaxFontSettings.hx) class.

If you are asking how to change the font size in Moonshine IDE, then please head over to the [Moonshine-IDE/Moonshine-IDE repository](https://github.com/Moonshine-IDE/Moonshine-IDE) instead.
