### ISSUE TITLE
Cursor jumps to import section when new import is added

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/moonshine-feathersui-text-editor#5]
There is quite annoying issue in editor where cursor after adding import is jumps to the added line. Below recording describes whole issue:

https://user-images.githubusercontent.com/24554795/143063218-3e938e1b-5344-4e37-b43c-0553c684242c.mov

**Version Moonshine Development:** 3.3.0 Build 2233

**Comment by joshtynjala** [comment]
This should not be happening. Thanks for letting me know. I'll take a look.

**Comment by piotrzarzycki21** [comment]
It's working - Tested on Moonshine Development 3.3.0 Build 2257
